### ISSUE TITLE
Problem with the import_workers.py script

### ISSUE THREAD

**Issue by Wesk00** [shrddr/workermanjs#7]
```
> python ./import_workers.py
using C:\Users\myusername\Documents\Black Desert\UserCache\35557\gamevariable.xml modified 2024-12-15 16:54:48.742185
parsed 134 worker names
using C:\Users\myusername\Documents\Black Desert\UserCache\35557\400\worker.cache modified 2024-12-15 16:54:48.748836
Traceback (most recent call last):
  File "C:\Users\myusername\Dateien\Games\Black Desert\workerman\import_workers.py", line 220, in <module>
    main()
  File "C:\Users\myusername\Dateien\Games\Black Desert\workerman\import_workers.py", line 213, in main
    parse_all(path)
  File "C:\Users\myusername\Dateien\Games\Black Desert\workerman\import_workers.py", line 189, in parse_all
    worker_list = parse_worker_data(cache, wid_names)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myusername\Dateien\Games\Black Desert\workerman\import_workers.py", line 154, in parse_worker_data
    assert version == 2, 'this version is probably not supported'
           ^^^^^^^^^^^^
AssertionError: this version is probably not supported
```

Did the structure of the worker.cache file change or is it a me problem?

**Comment by shrddr** [comment]
apparently with palace update new file version was introduced to support new job types

**Comment by shrddr** [comment]
you can probably put just version == 3 there or just remove the assert line altogether

**Comment by Wesk00** [comment]
I can make it skip the check and create a new file but the file isn't importable into workerman. Tried with a old file and it's working fine, so something seems wrong with the newly created one.

**Comment by shrddr** [comment]
well apparently the assert was correct and the format has changed, wait for someone to publish a new importer since this is out of this project scope for legal reasons
